services:
  api:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: docker/worker.dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
